services:
    - type: web
      name: django-ninja-react-vite
      env: docker
      plan: starter
      buildCommand: "" # No specific build command, as it's handled by Dockerfile
      startCommand: "" # No specific start command, as it's handled by Dockerfile

      # Docker setup
      dockerfilePath: ./Dockerfile # Path to Dockerfile

      # Static file configuration
      staticPublishPath: /backend/loa-moon/staticfiles # Path to collectstatic output folder in Django
      healthCheckPath: /api/health

      # Set auto-deploy on push to the main branch
      autoDeploy: true

      # Environment variables (sync with .env file on Render)
      secrets:
          - key: .env
            file: true # Use the secret file feature to mount a secret .env file securely

